name: Preprocess Avocado Ripeness Data

on:
  push:
    paths:
      - "data/avocado_ripeness_dataset.csv"
      - "preprocessing/automate_jafar-shodiq.py"
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy    - name: Debug Repository Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Repository content:"
        ls -la
        echo "Looking for dataset file:"
        find . -name "avocado_ripeness_dataset.csv"
        
    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_jafar-shodiq.py

    - name: Commit Processed Data
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add preprocessing/avocado_ripeness_dataset_preprocessed.csv
        git commit -m 'Update preprocessed avocado ripeness data' || echo "No changes to commit"
        git push
